name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**'] # for all submitted Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.12'
          - '8.13'
          - '8.14'
          - '8.15'
          - '8.16'
          - 'dev'
        ocaml_version:
          - 'default'
      fail-fast: false # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          before_install: |
            startGroup "Print opam config"
              opam pin -y coq-sqir https://github.com/inQWIRE/SQIR.git;
              opam pin -y coq-voqc https://github.com/inQWIRE/SQIR.git;
              opam config list; opam repo list; opam list
            endGroup
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}

