name: Static validation

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**'] # for all submitted Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      - name: execute static checks
        run: .hooks/pre-commit
